pull_request_rules:
  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=nix-flake-check
    actions:
      merge:
        method: rebase
